kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: bpg
nodes:
  - role: control-plane
    extraPortMappings:
      # PostgreSQL — audit ledger
      - containerPort: 30432
        hostPort: 5432
        protocol: TCP
      # OTLP gRPC — tracing ingest
      - containerPort: 30317
        hostPort: 4317
        protocol: TCP
      # OTLP HTTP — tracing ingest
      - containerPort: 30318
        hostPort: 4318
        protocol: TCP
      # Jaeger UI
      - containerPort: 30686
        hostPort: 16686
        protocol: TCP
